# Generated by Django 4.1.7 on 2023-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_number', models.IntegerField()),
                ('bsc_validation_status', models.CharField(choices=[('F', 'Failed'), ('U', 'Not validated'), ('V', 'Validated')], max_length=1)),
                ('data_type_code', models.CharField(choices=[(1, '027'), (2, '029'), (3, '033')], max_length=3, null=True)),
                ('site_visit_check_code', models.CharField(max_length=2, null=True)),
                ('site_visit_additional_information', models.CharField(max_length=200, null=True)),
                ('meter_serial_number', models.CharField(max_length=10)),
                ('reading_type', models.CharField(choices=[('A', 'Actual Change of Supplier Read'), ('C', 'Customer own read'), ('D', 'Deemed (Settlement Registers) or Estimated (Non-Settlement Registers)'), ('F', 'Final'), ('I', 'Initial'), ('R', 'MAR'), ('O', "Old Supplier's Estimated CoS Reading"), ('P', 'Electronically collected via PPMIP'), ('Q', 'Meter Reading modified manually by DC'), ('R', 'Routine'), ('S', 'Special'), ('T', 'Proving Test Reading'), ('W', 'Withdrawn'), ('Z', 'Actual Change of Tenancy Read')], max_length=1)),
                ('meter_register_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('md_reset_date_time', models.DateTimeField(null=True)),
                ('number_of_md_resets', models.IntegerField(null=True)),
                ('meter_reading_flag', models.BooleanField(choices=[(True, 'Valid'), (False, 'Suspect')], null=True)),
                ('reading_method', models.CharField(choices=[('N', 'Not viewed by an Agent or Non Site Visit'), ('P', 'Viewed by an Agent or Site Visit')], max_length=1)),
            ],
        ),
    ]
