# Generated by Django 4.1.7 on 2023-02-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_register_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('md_reset_date_time', models.DateTimeField(null=True)),
                ('number_of_md_resets', models.IntegerField(null=True)),
                ('meter_reading_flag', models.BooleanField(choices=[(True, 'Valid'), (False, 'Suspect')], null=True)),
                ('reading_method', models.CharField(choices=[('N', 'Not viewed by an Agent or Non Site Visit'), ('P', 'Viewed by an Agent or Site Visit')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='md_reset_date_time',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='meter_reading_flag',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='meter_register_id',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='number_of_md_resets',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='reading_date_time',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='reading_method',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter_reading_reason_code',
            field=models.CharField(choices=[('01', 'MSID Incorrect'), ('02', 'Reading Dates'), ('03', 'Negative Consumption'), ('04', 'Inconsistent with slave register advance'), ('05', 'Consumption exceeds twice expected advance'), ('06', 'Meter incorrectly energised'), ('07', 'Meter incorrectly de-energised'), ('08', 'Full Scale MD'), ('09', 'Zero MD'), ('10', 'Number of MD resets >1'), ('11', 'Number of register digits incorrect'), ('12', 'Inconsistent register read date'), ('13', 'Faulty Meter'), ('14', 'Hand Held Read Failure'), ('15', 'Meter Not on Site/Metering protocol not approved'), ('16', 'Standing Data incorrect'), ('17', 'No access to meter'), ('18', 'Meter Time/Date reset'), ('19', 'Outstation reset'), ('20', 'Meter Change/Meter Maintenance'), ('21', 'Phase Failure'), ('22', 'Meters Recording Zeros'), ('23', 'Test Data Recorded'), ('24', 'Data Lapse'), ('25', 'Actual Data Manually Keyed'), ('26', 'Invalid Zero Advances'), ('27', 'Zero Consumption')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter_reading_status',
            field=models.BooleanField(choices=[(True, 'Valid'), (False, 'Suspect')], null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='register_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter_readings.registerreading'),
        ),
    ]
