# Generated by Django 4.1.7 on 2023-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0002_registerreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='file_name',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
