# Generated by Django 4.1.7 on 2023-02-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0004_alter_meterreading_mpan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='register_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meter_readings.registerreading'),
        ),
    ]
