# Generated by Django 4.1.7 on 2023-02-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0005_alter_meterreading_register_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='data_type_code',
            new_name='site_visit_information_data_type_code',
        ),
    ]
