# Generated by Django 4.1.7 on 2023-02-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0006_rename_data_type_code_meterreading_site_visit_information_data_type_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='register_reading',
        ),
        migrations.AddField(
            model_name='registerreading',
            name='meter_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meter_readings.meterreading'),
        ),
    ]
