# Generated by Django 4.1.7 on 2023-02-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0007_remove_meterreading_register_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreading',
            name='meter_reading',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='meter_readings.meterreading'),
            preserve_default=False,
        ),
    ]
