# Generated by Django 4.1.7 on 2023-02-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0008_alter_registerreading_meter_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreading',
            name='meter_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_readings', to='meter_readings.meterreading'),
        ),
    ]
